# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 7, 2, 5, 45, 28, 135019, tzinfo=utc), verbose_name='\u767b\u8bb0\u65e5\u671f')),
                ('name', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('times', models.IntegerField(blank=True, null=True, verbose_name='\u767b\u8bb0\u6b21\u6570')),
                ('type', models.CharField(choices=[('dj', '\u767b\u8bb0'), ('zl', '\u6cbb\u7597')], max_length=2, verbose_name='\u8bb0\u5f55\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6ce8\u518c\u8bb0\u5f55',
                'verbose_name_plural': '\u6ce8\u518c\u8bb0\u5f55',
            },
        ),
    ]
