# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_num', models.IntegerField(verbose_name='\u5e8a\u4f4d\u53f7')),
                ('start_time', models.TimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.TimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('more_end_time', models.IntegerField(verbose_name='\u7ed3\u675f\u52a0\u65f6')),
                ('middle_time', models.TimeField(verbose_name='\u4e2d\u95f4\u65f6\u95f4')),
                ('more_middle_time', models.IntegerField(verbose_name='\u4e2d\u95f4\u52a0\u65f6')),
            ],
            options={
                'verbose_name': '\u8ba1\u65f6\u5668',
                'verbose_name_plural': '\u8ba1\u65f6\u5668',
            },
        ),
    ]
