# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='skip',
            field=models.BooleanField(default=False, verbose_name='\u6682\u65f6\u8df3\u8fc7'),
        ),
    ]
